### ISSUE TITLE
Command Tool Exceptions

### ISSUE THREAD

**Issue by jdgwartney** [cloudspace/rubberband_flamethrower#4]
[vagrant@centos-6-6 ~]$ flamethrower fire 2000 1 "http://es.com:9200"
/home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/rubberband_flamethrower-0.5.3/lib/rubberband_flamethrower/data_generator.rb:66:in `generate_random_insert_data': wrong number of arguments (0 for 1) (ArgumentError)
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/rubberband_flamethrower-0.5.3/lib/rubberband_flamethrower/flamethrower.rb:38:in`block in fire'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/rubberband_flamethrower-0.5.3/lib/rubberband_flamethrower/flamethrower.rb:36:in `times'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/rubberband_flamethrower-0.5.3/lib/rubberband_flamethrower/flamethrower.rb:36:in`fire'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/rubberband_flamethrower-0.5.3/lib/rubberband_flamethrower.rb:13:in `block in fire'
    from /home/vagrant/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/benchmark.rb:280:in`measure'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/rubberband_flamethrower-0.5.3/lib/rubberband_flamethrower.rb:12:in `fire'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/gems/rubberband_flamethrower-0.5.3/bin/flamethrower:14:in`<top (required)>'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/bin/flamethrower:23:in `load'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/bin/flamethrower:23:in`<main>'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
    from /home/vagrant/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in`<main>'

**Comment by captainkerk** [comment]
this issue was fixed in this PR: https://github.com/cloudspace/rubberband_flamethrower/pull/1/

However, it seems it never made it to the gem.

I got around it by changing the file directly after installing the gem

**Comment by beachwood23** [comment]
I'm still having issues with this. Any chance the Gem will be updated?
